##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  archlinux:
    # Useful URL: https://git.archlinux.org/svntogit/community.git/tree/libmateweather
    - autoconf-archive
    - clang
    - gcc
    - git
    - gtk3
    - libsoup
    - make
    - mate-common
    - tzdata
    - which

  debian:
    # Useful URL: https://github.com/mate-desktop/debian-packages
    # Useful URL: https://salsa.debian.org/debian-mate-team/libmateweather
    - autopoint
    - clang
    - clang-tools
    - cppcheck
    - gcc
    - git
    - gtk-doc-tools
    - libglib2.0-dev
    - libgtk-3-dev
    - libsoup-gnome2.4-dev
    - libsoup2.4-dev
    - libxml2-dev
    - libxml2-utils
    - make
    - mate-common
    - tzdata

  fedora:
    # Useful URL: https://src.fedoraproject.org/cgit/rpms/libmateweather.git
    - autoconf-archive
    - clang
    - clang-analyzer
    - gcc
    - git
    - gtk3-devel
    - libsoup-devel
    - libxml2-devel
    - make
    - mate-common
    - redhat-rpm-config
    - tzdata

  ubuntu:
    - autopoint
    - clang
    - clang-tools
    - gcc
    - git
    - gtk-doc-tools
    - libglib2.0-dev
    - libgtk-3-dev
    - libsoup-gnome2.4-dev
    - libsoup2.4-dev
    - libxml2-dev
    - libxml2-utils
    - make
    - mate-common
    - tzdata

variables:
  - 'CHECKERS="
    -enable-checker deadcode.DeadStores
    -enable-checker alpha.deadcode.UnreachableCode
    -enable-checker alpha.core.CastSize
    -enable-checker alpha.core.CastToStruct
    -enable-checker alpha.core.IdenticalExpr
    -enable-checker alpha.core.SizeofPtr
    -enable-checker alpha.security.ArrayBoundV2
    -enable-checker alpha.security.MallocOverflow
    -enable-checker alpha.security.ReturnPtrRange
    -enable-checker alpha.unix.SimpleStream
    -enable-checker alpha.unix.cstring.BufferOverlap
    -enable-checker alpha.unix.cstring.NotNullTerminated
    -enable-checker alpha.unix.cstring.OutOfBounds
    -enable-checker alpha.core.FixedAddr
    -enable-checker security.insecureAPI.strcpy"'

build_scripts:
  - NOCONFIGURE=1 ./autogen.sh
  - scan-build $CHECKERS ./configure
  - if [ $CPU_COUNT -gt 1 ]; then
  -     scan-build $CHECKERS --keep-cc -o html-report make -j $CPU_COUNT
  - else
  -     scan-build $CHECKERS --keep-cc -o html-report make
  - fi
  - if [ ${DISTRO_NAME} == "debian" ];then
  -     cppcheck --enable=warning,style,performance,portability,information,missingInclude .
  - fi

after_scripts:
  - make distcheck

releases:
  draft: false
  prerelease: false
  checksum: true
  file_glob: true
  files: libmateweather-*.tar.xz
  github_release:
    tags: true
    overwrite: true
    base_version: 1.20.0
    notify_servers:
      - https://release.mate-desktop.org/release
