#! /bin/sh

PACKAGE=libmateweather;

make -C po $PACKAGE.pot && mv po/$PACKAGE.pot .
sed -i "/#, fuzzy/d" $PACKAGE.pot

cd po-locations && ./regen.sh && rm Locations.xml.in.h && mv locations.pot .. && cd ..
